mopidy/mopidy-spotify

README.rst
mopidy_spotify/__init__.py
mopidy_spotify/backend.py
mopidy_spotify/ext.conf
tests/conftest.py
tests/test_backend.py
tests/test_extension.py

Hello. Thanks so much for Mopidy and the Spotify extension!
I occasionally find myself in situations in which I'd prefer my Spotify session to be private. This PR adds a `private_session` config value which can be used to do just that :smile:

config: Add private_session config

---

mopidy_spotify/lookup.py
tests/test_lookup.py

This should fix the issue described in #81. 
Perhaps we should be calling load on tracks for all the lookup routines? 
I'm not sure what to do with the test. I tried to swap `sp_playlist_mock` for `sp_unloaded_playlist_mock` but that's not working at all.

Ensure a playlist's tracks are all loaded when doing a lookup

---

README.rst
mopidy_spotify/__init__.py
mopidy_spotify/library.py
mopidy_spotify/search.py
mopidy_spotify/translator.py
tests/conftest.py
tests/test_search.py
tests/test_translator.py

This changes search to use the Web API, since search through libspotify doesn't work anymore.
It has some shortcomings, such as not having any artists for album results and returning unavailable tracks, but it's a first step. See the commit messages for details.
I see that the old search is used in distinct as well, but I don't know where that's used from, and haven't looked at that yet. This fixes the normal search at least.
I'm creating the PR against master, because I'm thinking we may want to create a bugfix release for use against the current version of Mopidy. (Should we have a release-2.3 branch?)
Fixes #89.

Use the Web API for search

---

mopidy_spotify/distinct.py
mopidy_spotify/library.py
mopidy_spotify/search.py
tests/conftest.py
tests/test_distinct.py
tests/test_search.py

Previously, distinct searched directly with pyspotify when given a query argument. This changes it to use the internal search method, which has been changed to using Spotifys Web API.

Use Spotifys Web API for distinct

---

CHANGES.rst
mopidy_spotify/translator.py
tests/conftest.py
tests/test_translator.py

Spotifys Web API now includes the artists of each album in the search
results.

search: Include the artists for each album in the search results

---

README.rst

I had an issue when creating a device-specific password, because the Spotify website kept crashing. I suspect it's because I have a facebook-only login, and I suspect I'm not alone on this one. I managed to get everything working by following the steps outlined in the updated text.

Update README in case Spotify website breaks on device password

---

README.rst
mopidy_spotify/__init__.py
mopidy_spotify/backend.py
mopidy_spotify/distinct.py
mopidy_spotify/ext.conf
mopidy_spotify/images.py
mopidy_spotify/library.py
mopidy_spotify/search.py
mopidy_spotify/utils.py
mopidy_spotify/web.py
tests/conftest.py
tests/test_backend.py
tests/test_images.py
tests/test_search.py
tests/test_web.py

Fixes and tests for @adamcik's original branch.
Still need to consider (from #130):

OAuth support for accessing Web API endpoints

---

mopidy_spotify/browse.py
mopidy_spotify/distinct.py
mopidy_spotify/lookup.py
mopidy_spotify/playlists.py
mopidy_spotify/translator.py
tests/test_lookup.py
tests/test_playlists.py

As per #129, `load` calls were not respecting user configured timeout.

Make load calls respect timeout

---

mopidy_spotify/search.py
tests/conftest.py
tests/test_search.py

This fixes #97 by setting the market parameter when doing searches using the Web API.
We don't currently set the parameter and it defaults to 'US' (https://github.com/spotify/web-api/issues/194). Depending on the logged in user's country, this may result in missing or unavailable tracks being returned. For example "The black box revelation" as reported in https://github.com/mopidy/mopidy-spotify/issues/106.
I appreciate that considering https://github.com/mopidy/mopidy-spotify/issues/130, this might not see the light of day, but at least this should remind us to set it as part of those future changes.

Fix missing / unavailable tracks in search results

---

mopidy_spotify/playback.py
tests/test_playback.py

Previously, when paused, we stopped consuming audio buffers rather than telling libspotify to pause playback. This lead to undesirable behaviour on other clients if the "paused" mopidy-spotify instance was offline at the time playback was started on another Spotify client, causing it to miss the playback token lost signal from the other client (see #146).

Pause spotify playback when Mopidy paused

---

dev-requirements.txt
tests/conftest.py
tests/test_backend.py
tests/test_lookup.py
tests/test_playlists.py
tests/test_search.py
tests/test_translator.py
tests/test_utils.py
tests/test_web.py

* pytest-capturelog plugin was merged into pytest core.
* caplog.text is no longer callable.
* pytest captures log messages of level WARNING or above, we need lower.

Updated tests for breaking changes in latest pytest.

---

tests/conftest.py
tests/test_browse.py
tests/test_playback.py
tests/test_utils.py

This became an error in pytest v4.1.0. See https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
Also flake8 fix for now invalid escape sequence.

Workarounds for where we call fixures directly.

---

tests/test_backend.py

When asserting `mock.call in list(some_call)`, the `some_call` ends up on the lhs.
In our failing test cases, the `some_call` on the lhs includes an `ActorProxy` and the `mock.call` on the rhs includes the `mock.ANY`, so we get `ActorProxy.__eq__(mock.ANY)`, [which returns False](https://github.com/jodal/pykka/blob/develop/pykka/_proxy.py#L186-L188).
In Pykka 1.x there was no `ActorProxy.__eq__()` defined so we ended up doing `mock.ANY.__eq__(ActorProxy)`, [which returned True](https://github.com/python/cpython/blob/2.7/Lib/test/_mock_backport.py#L1880). This PR avoids this situation.

Fix backend tests compatibility with pykka 2.0.

---

mopidy_spotify/web.py
tests/conftest.py
tests/test_web.py

This adds caching to the web client and is required for decent performance when using Spotify's Web API for playlist data (https://github.com/mopidy/mopidy-spotify/issues/182, https://github.com/mopidy/mopidy-spotify/pull/188).
This supports expiry times calculated from the [Cache-Control header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) as well as [ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) to detect unmodified response data once it's expired.
This part of the fix is self-contained and it seemed reasonable to split it out. I think I've also improved the code in doing so. Hopefully this will also make reviewing easier.

Web client caching

---

.travis.yml
tox.ini

Use the default Travis build environment, which is now Xenial rather than Trusty (Python 2.7.12).

Use latest travis/tox receipes

---

mopidy_spotify/web.py
tests/test_web.py

Python 3 fix: '>=' not supported between instances of 'NoneType' and 'int'

Ensure status code is valid before using it.

---

CHANGELOG.rst
README.rst
mopidy_spotify/__init__.py
mopidy_spotify/backend.py
mopidy_spotify/browse.py
mopidy_spotify/distinct.py
mopidy_spotify/library.py
mopidy_spotify/lookup.py
mopidy_spotify/playback.py
mopidy_spotify/playlists.py
mopidy_spotify/search.py
mopidy_spotify/translator.py
mopidy_spotify/utils.py
mopidy_spotify/web.py
tests/conftest.py
tests/test_backend.py
tests/test_browse.py
tests/test_distinct.py
tests/test_images.py
tests/test_lookup.py
tests/test_playback.py
tests/test_playlists.py
tests/test_search.py
tests/test_translator.py
tests/test_web.py

Third time lucky here. This is the Python 3 version of https://github.com/mopidy/mopidy-spotify/pull/228 aimed at fixing #140 and #182. Everything discussed in the previous PR is probably still valid for this version.
I have redone the performance measurements that I included in the commits for #228 which helped explained the code's evolution.
I'm *still* not happy with returning the raw (mutable) cache data dict to `SpotifyOAuthClient` and this led to the hacky workaround: https://github.com/mopidy/mopidy-spotify/blob/681debe77d46d233f792c7e64b1c76fc7bfff71e/mopidy_spotify/web.py#L462-L465. Returning something immutable like a `namedtuple` might be better or something Python 3-ish (dataclass?).

Web API playlists v3

---

CHANGELOG.rst
README.rst
mopidy_spotify/browse.py
mopidy_spotify/library.py
mopidy_spotify/translator.py
tests/test_browse.py
tests/test_translator.py

Personal top albums are not available using the Web API.
Also pushed the toplists down a directory level ready for adding the functionality from mopidy-spotify-web.

Use Web API for personal top tracks and artists.

---

CHANGELOG.rst
README.rst
mopidy_spotify/browse.py
mopidy_spotify/translator.py
tests/test_browse.py
tests/test_translator.py

Thought I needed to rejig the translator to support simple and full web objects. However, it actually turns out can get away with not doing that since can still load albums using libspotify. So have ripped that back out to simplify this change. 
Done tests.

Support browsing of albums and tracks from the "Your music" library

---

mopidy_spotify/browse.py
mopidy_spotify/utils.py
tests/test_browse.py

Load all tracks in "Your Music", "Playlists" and "Top Lists"

---

mopidy_spotify/playback.py
tests/test_playback.py

This is #269 with the remaining CI fixes. And also with the held buffer changed from a global to an instance variable as the `music_delivery_callback` tests were no longer doing the right thing.

Soaku gapless playback

---

mopidy_spotify/translator.py
tests/test_translator.py

We can't do anything sensible without a URI so also ignore anything where it is ` None`. This occurs in the album and artist fields within local Spotify tracks (from a playlist).
Without this we try and translate the artist and album fields, which isn't useful and in the case of changes in https://github.com/mopidy/mopidy-spotify/pull/287/ actually causes an exception.

Ignore parts of web responses with a None URI.

---

tests/conftest.py
tests/test_web.py

During review/testing of https://github.com/mopidy/mopidy-spotify/pull/287 I realised there's a potential problem with the way we mix relative and absolute URLs when using the web client when it comes to trying to clear specific parts of the cache. So I wanted to be a lot more explicit in the tests and and have the URLs we use more closely match reality. This will be helpful for the PR that addresses this issue.
Plus a fix I had been sitting on for a while which uses the `skip_refresh_token` in the other places it's useful (rather than directly messing about with numbers).

Improve web tests

---

mopidy_spotify/web.py
tests/test_web.py

For logged in user 'foo',  Web API endpoint "me/playlists"
returns the same as "users/foo/playlists" (including headers).
When we use the former, the "next" links in the response always use
the latter. This leaves us with a mix of URL formats in our cache
and will make identifying/invalidating these entries harder.
This change ensures all the URLs look the same. No behaviour has
changed.
This will make cache invalidation in #287 a little simpler and makes sense to do anyway.

Use the long-form Spotify URL for user playlists.

---

mopidy_spotify/playlists.py

I have ~1k playlists on my account so a refresh takes about 8 minutes.
The logs gives no indication what is happening and I was confused so
providing an explanation to what is happening would have been useful.
PS. Thanks for a great project! I use mopidy on an RPi and connect it to a bluetooth speaker to always have music playing in my bathroom 🎶

Log when refresh of playlists starts

---

mopidy_spotify/search.py
tests/test_search.py

Fixes #280.
Empty (None) Mopidy models were created due to malformed data /
unplayable tracks returned by search endpoint. Must be filtered
out before adding to SearchResults to avoid validation errors.

search: Remove empty tracks/albums/artists from search results.

---

mopidy_spotify/search.py
mopidy_spotify/translator.py
tests/test_search.py
tests/test_translator.py

Because the `sp_search_query` function has always added double quotes around the query and double quotes instruct the Spotify API to perform exact matching, the `search` function has always performed exact matching, regardless of whether `exact` is `False` or `True`.
https://github.com/mopidy/mopidy-spotify/blob/a4aa63adb291d0c3a6f5af53fe466564b2e4c878/mopidy_spotify/translator.py#L283-L286
Since exact matching has been the only behavior (and therefore the default behavior) since the inception of Mopidy-Spotify, it could be sensible to keep exact matching as the default behavior. However, according to the [Mopidy documentation](https://docs.mopidy.com/en/latest/api/core/#mopidy.core.LibraryController.search), inexact matching is supposed to be the default behavior.

Do not ignore the `exact` parameter in the `search` method

---

mopidy_spotify/browse.py
mopidy_spotify/lookup.py
mopidy_spotify/web.py
tests/test_lookup.py
tests/test_web.py

This adds the ability to utilise the "spotify:your:tracks" and
"spotify:your:albums" URIs through library lookups.

Support lookups for 'your' URIs

---

mopidy_spotify/backend.py
tests/test_playback.py

Always cache credentials and use dedicated folder for credentials cache. Folder for credentials cache has mode 700.
For #353

Improve credentials cache

---

mopidy_spotify/web.py

This stopped working for no reason. Spotify have ignored my bug report.

Fix Spotify's field syntax change

---

mopidy_spotify/translator.py
tests/test_translator.py

Weirdly Spotify API has started returning floats instead of ints. Let's just handle it.

Fix floats in API response (Fixes #375)

---

src/mopidy_spotify/playlists.py
src/mopidy_spotify/web.py
tests/__init__.py
tests/test_backend.py
tests/test_playlists.py
tests/test_web.py

I think this is the best of both worlds since it gets the playlist names immediately, avoids blocking Mopidy startup, but still gathers the track info in the background to make everything snappy later on.

Fix startup time

---

src/mopidy_spotify/library.py
tests/test_lookup.py

This is only a bodge until we do a release and just helps in the cases where people are still installing from git like I originally suggested they did, and so pip brings in the required Mopidy v4 dep but it doesn't actually get used and their mopidy service is still using Mopidy v3 (which doesn't support `lookup_many`.

Temporary hack for Mopidy v4 installations

---

src/mopidy_spotify/commands.py

Somehow, despite passing all tests, this didn't atually work with Mopidy 4.0 Also re-instating PR feedback that got lost with forced push.

Fixes for logout command
